services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: klover-dev

    working_dir: /workspace

    environment:
      KLOVER_CORE_DIR: /workspace/build/core
      CARGO_TARGET_DIR: /workspace/build/cargo

    volumes:
      - .:/workspace
      - cargo-registry:/root/.cargo/registry
      - cargo-git:/root/.cargo/git

    stdin_open: true
    tty: true

volumes:
  cargo-registry:
  cargo-git:
