[package]
name = "klover"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
"bitflags" = "2.11.1"
"byteorder" = "1"
"cafebabe" = "0.9.0"
"cesu8" = "1.1"
"dashmap" = "6.2.1"
"parking_lot" = "0.12.5"

# Expose subsystem paths only for external integration tests.
[features]
integration-tests = []

[[test]]
name = "jvm"
path = "tests/jvm.rs"
required-features = ["integration-tests"]
